name: 'Run ktlint with reviewdog'
description: '🐶 Run ktlint with reviewdog on pull requests to enforce best practices'
author: 'renatoabreu11 (ScaCap)'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    required: false
    default: 'false'
  relative:
    description: Print files relative to the working directory
    required: false
    default: 'true'
  android:
    description: Run Ktlint with Android Kotlin Style Guide
    required: false
    default: 'false'
  baseline:
    description: Use a baseline configuration
    required: false
    default: ''
  ktlint_version:
    description: Defines the ktlint version to use
    required: false
    default: 'latest'
  file_glob:
    description: Optionally defines a file glob to identify files to be checked
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
    - ${{ inputs.fail_on_error }}
    - ${{ inputs.filter_mode }}
    - ${{ inputs.relative }}
    - ${{ inputs.android }}
    - ${{ inputs.baseline }}
    - ${{ inputs.ktlint_version }}
    - ${{ secrets.GITHUB_TOKEN }}
branding:
  icon: 'edit'
  color: 'blue'
